from collections.abc import Awaitable, Callable

from src.tools.cleanup import delete_archived_shared_steps, delete_archived_test_cases, delete_unused_custom_fields
from src.tools.create_custom_field_value import create_custom_field_value
from src.tools.create_test_case import create_test_case
from src.tools.defects import (
    create_defect,
    create_defect_matcher,
    delete_defect,
    delete_defect_matcher,
    get_defect,
    link_defect_to_test_case,
    list_defect_matchers,
    list_defect_test_cases,
    list_defects,
    unlink_issue_from_test_case,
    update_defect,
    update_defect_matcher,
)
from src.tools.delete_custom_field_value import delete_custom_field_value
from src.tools.delete_test_case import delete_test_case
from src.tools.get_custom_fields import get_custom_fields
from src.tools.get_test_case_custom_fields import get_test_case_custom_fields
from src.tools.launches import (
    add_test_result_attachment,
    add_test_step_attachment,
    close_launch,
    create_launch,
    delete_launch,
    get_launch,
    list_launch_test_results,
    list_launches,
    reopen_launch,
    rerun_test_results_manually,
    start_manual_test_session,
    submit_manual_test_results,
    upload_test_results,
)
from src.tools.link_shared_step import link_shared_step
from src.tools.list_custom_field_values import list_custom_field_values
from src.tools.list_integrations import list_integrations
from src.tools.output_contract import ToolOutput
from src.tools.plans import (
    create_test_plan,
    delete_test_plan,
    list_test_plans,
    manage_test_plan_content,
    update_test_plan,
)
from src.tools.search import get_test_case_details, list_test_cases, search_test_cases
from src.tools.shared_steps import create_shared_step, delete_shared_step, list_shared_steps, update_shared_step
from src.tools.test_layers import (
    assign_test_cases_to_suite,
    create_test_layer,
    create_test_layer_schema,
    create_test_suite,
    delete_test_layer,
    delete_test_layer_schema,
    delete_test_suite,
    list_test_layer_schemas,
    list_test_layers,
    list_test_suites,
    update_test_layer,
    update_test_layer_schema,
)
from src.tools.unlink_shared_step import unlink_shared_step
from src.tools.update_custom_field_value import update_custom_field_value
from src.tools.update_test_case import update_test_case

__all__ = [
    "add_test_result_attachment",
    "add_test_step_attachment",
    "assign_test_cases_to_suite",
    "close_launch",
    "create_custom_field_value",
    "create_defect",
    "create_defect_matcher",
    "create_launch",
    "create_shared_step",
    "create_test_case",
    "create_test_layer",
    "create_test_layer_schema",
    "create_test_plan",
    "create_test_suite",
    "delete_archived_shared_steps",
    "delete_archived_test_cases",
    "delete_custom_field_value",
    "delete_defect",
    "delete_defect_matcher",
    "delete_launch",
    "delete_shared_step",
    "delete_test_case",
    "delete_test_layer",
    "delete_test_layer_schema",
    "delete_test_plan",
    "delete_test_suite",
    "delete_unused_custom_fields",
    "get_custom_fields",
    "get_defect",
    "get_launch",
    "get_test_case_custom_fields",
    "get_test_case_details",
    "link_defect_to_test_case",
    "link_shared_step",
    "list_custom_field_values",
    "list_defect_matchers",
    "list_defect_test_cases",
    "list_defects",
    "list_integrations",
    "list_launch_test_results",
    "list_launches",
    "list_shared_steps",
    "list_test_cases",
    "list_test_layer_schemas",
    "list_test_layers",
    "list_test_plans",
    "list_test_suites",
    "manage_test_plan_content",
    "reopen_launch",
    "rerun_test_results_manually",
    "search_test_cases",
    "start_manual_test_session",
    "submit_manual_test_results",
    "unlink_issue_from_test_case",
    "unlink_shared_step",
    "update_custom_field_value",
    "update_defect",
    "update_defect_matcher",
    "update_shared_step",
    "update_test_case",
    "update_test_layer",
    "update_test_layer_schema",
    "update_test_plan",
    "upload_test_results",
]

ToolFn = Callable[..., Awaitable[ToolOutput]]

all_tools: list[ToolFn] = [
    create_test_case,
    get_test_case_details,
    update_test_case,
    delete_test_case,
    delete_archived_test_cases,
    list_test_cases,
    get_custom_fields,
    delete_unused_custom_fields,
    list_custom_field_values,
    create_custom_field_value,
    update_custom_field_value,
    delete_custom_field_value,
    get_test_case_custom_fields,
    search_test_cases,
    create_launch,
    get_launch,
    list_launches,
    list_launch_test_results,
    rerun_test_results_manually,
    start_manual_test_session,
    submit_manual_test_results,
    upload_test_results,
    add_test_result_attachment,
    add_test_step_attachment,
    delete_launch,
    close_launch,
    reopen_launch,
    # Integration Tools
    list_integrations,
    create_shared_step,
    list_shared_steps,
    update_shared_step,
    delete_shared_step,
    delete_archived_shared_steps,
    link_shared_step,
    unlink_shared_step,
    # Test Layer Tools
    list_test_layers,
    create_test_layer,
    update_test_layer,
    delete_test_layer,
    list_test_layer_schemas,
    create_test_layer_schema,
    update_test_layer_schema,
    delete_test_layer_schema,
    # Test Hierarchy Tools
    create_test_suite,
    list_test_suites,
    assign_test_cases_to_suite,
    delete_test_suite,
    # Test Plan Tools
    create_test_plan,
    update_test_plan,
    manage_test_plan_content,
    list_test_plans,
    delete_test_plan,
    # Defect Management Tools
    create_defect,
    get_defect,
    link_defect_to_test_case,
    list_defect_test_cases,
    unlink_issue_from_test_case,
    update_defect,
    delete_defect,
    list_defects,
    create_defect_matcher,
    update_defect_matcher,
    delete_defect_matcher,
    list_defect_matchers,
]

# Output fields belong to their registered tool definitions.  ``output_schemas``
# consumes this metadata; it never maintains a second list of tool names.
_COLLECTION_OUTPUT_FIELDS = ("items", "total", "page", "size", "total_pages")
_LAUNCH_OUTPUT_FIELDS = (
    "id",
    "name",
    "closed",
    "created_date",
    "last_modified_date",
    "project_id",
    "autoclose",
    "external",
    "known_defects_count",
    "new_defects_count",
    "manual_execution_guidance",
    "url",
    "operation",
)
_TEST_CASE_LIST_OUTPUT_FIELDS = ("total", "page", "size", "total_pages", "items")

_OUTPUT_FIELDS_BY_TOOL: dict[ToolFn, tuple[str, ...]] = {
    add_test_result_attachment: ("target_kind", "target_id", "file_names", "status_code"),
    add_test_step_attachment: ("target_kind", "target_id", "file_names", "status_code"),
    assign_test_cases_to_suite: ("tree_id", "suite_id", "test_case_ids", "assigned_count"),
    close_launch: _LAUNCH_OUTPUT_FIELDS,
    create_custom_field_value: ("id", "name", "custom_field_id", "custom_field_name"),
    create_defect: ("id", "name", "description", "url"),
    create_defect_matcher: ("id", "defect_id", "name", "message_regex", "trace_regex"),
    create_launch: _LAUNCH_OUTPUT_FIELDS,
    create_shared_step: ("id", "name", "project_id", "url"),
    create_test_case: ("id", "name", "issues", "url"),
    create_test_layer: ("id", "name"),
    create_test_layer_schema: ("id", "key", "test_layer_id", "test_layer_name"),
    create_test_plan: ("id", "name", "aql_filter", "test_case_ids", "test_case_urls", "url"),
    create_test_suite: ("id", "name", "tree_id", "parent_suite_id"),
    delete_archived_shared_steps: ("deleted_count",),
    delete_archived_test_cases: ("deleted_count",),
    delete_custom_field_value: ("requires_confirmation", "action", "cfv_id", "id", "status"),
    delete_defect: ("defect_id", "id", "status", "url"),
    delete_defect_matcher: ("matcher_id", "id", "status"),
    delete_launch: ("launch_id", "status", "message"),
    delete_shared_step: ("requires_confirmation", "action", "step_id", "id", "status", "url"),
    delete_test_case: ("requires_confirmation", "action", "test_case_id", "name", "status", "error", "url"),
    delete_test_layer: ("requires_confirmation", "action", "layer_id", "id", "status"),
    delete_test_layer_schema: ("requires_confirmation", "action", "schema_id", "id", "status"),
    delete_test_plan: ("requires_confirmation", "action", "plan_id", "status", "url"),
    delete_test_suite: ("requires_confirmation", "action", "suite_id", "status"),
    delete_unused_custom_fields: ("deleted_count",),
    get_custom_fields: ("items", "total", "filter_name"),
    get_defect: ("id", "name", "description", "status", "closed", "url"),
    get_launch: _LAUNCH_OUTPUT_FIELDS,
    get_test_case_custom_fields: ("test_case_id", "custom_fields"),
    get_test_case_details: (
        "id",
        "name",
        "status",
        "description",
        "precondition",
        "tags",
        "custom_fields",
        "attachments",
        "steps",
        "url",
    ),
    link_defect_to_test_case: (
        "defect_id",
        "defect_url",
        "test_case_id",
        "test_case_url",
        "integration_id",
        "issue_key",
        "already_linked",
    ),
    link_shared_step: (
        "requires_confirmation",
        "action",
        "test_case_id",
        "test_case_url",
        "shared_step_id",
        "shared_step_url",
        "steps",
        "status",
        "error",
    ),
    list_custom_field_values: _COLLECTION_OUTPUT_FIELDS,
    list_defect_matchers: ("defect_id", *_COLLECTION_OUTPUT_FIELDS),
    list_defect_test_cases: ("defect_id", "defect_url", *_COLLECTION_OUTPUT_FIELDS),
    list_defects: _COLLECTION_OUTPUT_FIELDS,
    list_integrations: ("items", "total"),
    list_launch_test_results: ("launch_id", "manual_only", "failed_only", *_COLLECTION_OUTPUT_FIELDS),
    list_launches: _COLLECTION_OUTPUT_FIELDS,
    list_shared_steps: _COLLECTION_OUTPUT_FIELDS,
    list_test_cases: _TEST_CASE_LIST_OUTPUT_FIELDS,
    list_test_layer_schemas: _COLLECTION_OUTPUT_FIELDS,
    list_test_layers: _COLLECTION_OUTPUT_FIELDS,
    list_test_plans: _COLLECTION_OUTPUT_FIELDS,
    list_test_suites: ("tree", "items", "total"),
    manage_test_plan_content: (
        "plan_id",
        "add_test_case_ids",
        "remove_test_case_ids",
        "aql_filter",
        "add_test_case_urls",
        "remove_test_case_urls",
        "url",
    ),
    reopen_launch: _LAUNCH_OUTPUT_FIELDS,
    rerun_test_results_manually: ("launch_id", "result_ids", "scheduled_count", "assignees", "force_manual"),
    search_test_cases: (*_TEST_CASE_LIST_OUTPUT_FIELDS, "query"),
    start_manual_test_session: ("test_session_id", "launch_id", "job_id", "job_run_id", "project_id", "environment"),
    submit_manual_test_results: ("test_session_id", "result_ids", "submitted_count"),
    unlink_issue_from_test_case: ("test_case_id", "issue_id", "status", "already_unlinked"),
    unlink_shared_step: (
        "requires_confirmation",
        "action",
        "test_case_id",
        "test_case_url",
        "shared_step_id",
        "shared_step_url",
        "steps",
        "status",
        "error",
    ),
    update_custom_field_value: (
        "requires_confirmation",
        "action",
        "cfv_id",
        "id",
        "name",
        "custom_field_id",
        "custom_field_name",
    ),
    update_defect: ("id", "name", "description", "status", "closed", "url"),
    update_defect_matcher: ("id", "name", "message_regex", "trace_regex"),
    update_shared_step: (
        "requires_confirmation",
        "action",
        "step_id",
        "id",
        "name",
        "changed",
        "updated_fields",
        "url",
    ),
    update_test_case: ("requires_confirmation", "action", "test_case_id", "id", "name", "summary", "changes", "url"),
    update_test_layer: ("requires_confirmation", "action", "layer_id", "id", "name", "changed"),
    update_test_layer_schema: (
        "requires_confirmation",
        "action",
        "schema_id",
        "id",
        "key",
        "test_layer_name",
        "changed",
    ),
    update_test_plan: ("id", "name", "url"),
    upload_test_results: ("launch_id", "requested_count", "uploaded_count", "result_ids", "failures"),
}


def output_fields_for(tool: ToolFn) -> tuple[str, ...]:
    """Return the explicitly declared output fields for a registered tool."""
    try:
        return _OUTPUT_FIELDS_BY_TOOL[tool]
    except KeyError as exc:
        raise ValueError(f"No output fields registered for tool '{tool.__name__}'") from exc


def validate_output_field_coverage() -> None:
    """Ensure the output field metadata stays synchronized with ``all_tools``."""
    registered = set(all_tools)
    declared = set(_OUTPUT_FIELDS_BY_TOOL)
    if registered != declared:
        missing = sorted(tool.__name__ for tool in registered - declared)
        stale = sorted(tool.__name__ for tool in declared - registered)
        raise RuntimeError(f"Output field coverage mismatch; missing={missing}, stale={stale}")
